# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backgroud Noise Removal

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'Lint code'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Run Docker Compose and pytest
      env:
        ENV: "testing"
      run: |
        docker-compose up -d
        pytest 

    # - name: Test with pytest
    #   run: |
    #     pytest

  
  # server:
  #   name: Push to Digital Ocean Server
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Deploy to DigitalOcean
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_STAGING_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         port: ${{ secrets.SSH_PORT }}
  #         # password: ${{ secrets.SSH_PASSWORD }}
  #         key: ${{ secrets.SSH_KEY }}
  #         passphrase: ${{ secrets.PASS_PHRASE }}
  #         script: |
  #           cd /home/salesengine/salesngineservices
  #           git stash
  #           git pull
  #           sudo chmod 666 /var/run/docker.sock
  #           docker container stop
  #           docker-compose up --build -d
